export const PATH = {
  LOGIN: "/login",
  HOME: "/home",
  LANDING: "/",
  COURSES: "/courses",
  COURSES_OVERVIEW: "/courses/overview/:courseId",
  COURSES_DETAIL: "/courses/detail/:courseId",
  QUIZ: "/quizzes/:quizId",
  TOURNAMENT: "/tournaments",
  TOURNAMENT_ROOM: "/tournaments/:tournamentId",
  TOURNAMENT_WAITING_ROOM: "/rooms/:roomId",
  TOURNAMENT_MATCH: "/match",
  TOURNAMENT_MATCH_HISTORY: "/match-histories",
  LEADER_BOARD: "/leaderboard",
  CERTIFICATE: "/certificates",
  CERTIFICATE_DETAIL: "/certificates/:certificateId",
  METRIC: "/metrics",
  PROFILE: "/profile",
  FORBIDDEN: "/403",
  NOT_FOUND: "/404",
  INTERNAL_SERVER_ERROR: "/500",
};
