export const PATH = {
  LOGIN: "/login",
  HOME: "/home",
  LANDING: "/",
  COURSES: "/courses",
  COURSES_OVERVIEW: "/courses/overview/:courseId",
  COURSES_DETAIL: "/courses/detail/:courseId",
  QUIZ: "/quizzes/:quizId",
  CHALLENGE: "/challenges",
  CERTIFICATE: "/certificates",
  CERTIFICATE_DETAIL: "/certificates/:certificateId",
  FORBIDDEN: "/403",
  NOT_FOUND: "/404",
  INTERNAL_SERVER_ERROR: "/500",
};
